name: Update Repo

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Timestamp
        id: timestamp
        run: |
          echo "timestamp=$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout New Branch
        run: |
          git checkout -b update-${{ steps.timestamp.outputs.timestamp }}
      - name: Checkout OrnaCodexCrawler
        uses: actions/checkout@v4
        with: 
          repository: '67au/OrnaCodexCrawler'
          path: './crawler'
      - name: Download Codex From Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: codex
          path: './crawler/output'
          branch: main
          workflow: crawl.yml
          github_token: ${{ secrets.GH_PAT }}
          repo: 67au/OrnaCodexCrawler
      - name: Setup Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13
      - run: uv sync --directory ./crawler
      - name: Update Repo
        run: uv run --directory ./crawler main.py update_extra --extra ../data
      - name: Push Changes
        shell: bash
        run: |
          git add data
          if [ ! -z "$(git --no-pager diff --staged)" ]; then
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -s -m "Data Update $(date +%Y%m%d%H%M)" -a
            git push
          fi
  
